{{- if and .Values.concierge.enabled .Values.concierge.credentialIssuer.create }}
apiVersion: config.concierge.pinniped.dev/v1alpha1
kind: CredentialIssuer
metadata:
  name: pinniped-concierge-config
  labels:
    {{- include "pinniped.concierge.labels" . | nindent 4 }}
  {{- with .Values.concierge.credentialIssuer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- required "concierge.credentialIssuer.spec must not be empty" .Values.concierge.credentialIssuer.spec | toYaml | nindent 2 }}
{{- end }}
