{{- if .Values.concierge.enabled }}
{{- $ns := include "pinniped.concierge.namespace" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinniped-concierge
  namespace: {{ $ns }}
  labels:
    {{- include "pinniped.concierge.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinniped-concierge-kube-cert-agent
  namespace: {{ $ns }}
  labels:
    {{- include "pinniped.concierge.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinniped-concierge-impersonation-proxy
  namespace: {{ $ns }}
  labels:
    {{- include "pinniped.concierge.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
secrets: []
automountServiceAccountToken: false
{{- end }}
