{{- if .Values.supervisor.enabled }}
{{- range .Values.supervisor.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "each supervisor.secrets entry needs a name" .name }}
  namespace: {{ include "pinniped.supervisor.namespace" $ }}
  labels:
    {{- include "pinniped.supervisor.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .type | default "secrets.pinniped.dev/oidc-client" }}
stringData:
  {{- required "each supervisor.secrets entry needs stringData" .stringData | toYaml | nindent 2 }}
{{- end }}
{{- end }}
