{{- if .Values.supervisor.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinniped-supervisor
  namespace: {{ include "pinniped.supervisor.namespace" . }}
  labels:
    {{- include "pinniped.supervisor.labels" . | nindent 4 }}
{{- end }}
